/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('city').del()
  await knex('city').insert([
    { id: 1, name: 'Ahuachapán', state_id: 4 },
    { id: 2, name: 'Apaneca', state_id: 4 },
    { id: 3, name: 'Atiquizaya', state_id: 4 },
    { id: 4, name: 'Concepción de Ataco', state_id: 4 },
    { id: 5, name: 'El Refugio', state_id: 4 },
    { id: 6, name: 'Guaymango', state_id: 4 },
    { id: 7, name: 'Jujutla', state_id: 4 },
    { id: 8, name: 'San Francisco Menéndez', state_id: 4 },
    { id: 9, name: 'San Lorenzo', state_id: 4 },
    { id: 10, name: 'San Pedro Puxtla', state_id: 4 },
    { id: 11, name: 'Tacuba', state_id: 4 },
    { id: 12, name: 'Turín', state_id: 4 },
    { id: 13, name: 'Candelaria de la Frontera', state_id: 6 },
    { id: 14, name: 'Chalchuapa', state_id: 6 },
    { id: 15, name: 'Coatepeque', state_id: 6 },
    { id: 16, name: 'El Congo', state_id: 6 },
    { id: 17, name: 'El Porvenir', state_id: 6 },
    { id: 18, name: 'Masahuat', state_id: 6 },
    { id: 19, name: 'Metapán', state_id: 6 },
    { id: 20, name: 'San Antonio Pajonal', state_id: 6 },
    { id: 21, name: 'San Sebastián Salitrillo', state_id: 6 },
    { id: 22, name: 'Santa Ana', state_id: 6 },
    { id: 23, name: 'Santa Rosa Guachipilín', state_id: 6 },
    { id: 24, name: 'Santiago de la Frontera', state_id: 6 },
    { id: 25, name: 'Texistepeque', state_id: 6 },
    { id: 26, name: 'Acajutla', state_id: 7 },
    { id: 27, name: 'Armenia', state_id: 7 },
    { id: 28, name: 'Caluco', state_id: 7 },
    { id: 29, name: 'Cuisnahuat', state_id: 7 },
    { id: 30, name: 'Izalco', state_id: 7 },
    { id: 31, name: 'Juayúa', state_id: 7 },
    { id: 32, name: 'Nahuizalco', state_id: 7 },
    { id: 33, name: 'Nahulingo', state_id: 7 },
    { id: 34, name: 'Salcoatitán', state_id: 7 },
    { id: 35, name: 'San Antonio del Monte', state_id: 7 },
    { id: 36, name: 'San Julián', state_id: 7 },
    { id: 37, name: 'Santa Catarina Masahuat', state_id: 7 },
    { id: 38, name: 'Santa Isabel Ishuatán', state_id: 7 },
    { id: 39, name: 'Santo Domingo Guzmán', state_id: 7 },
    { id: 40, name: 'Sonsonate', state_id: 7 },
    { id: 41, name: 'Sonzacate', state_id: 7 },
    { id: 42, name: 'Agua Caliente', state_id: 3 },
    { id: 43, name: 'Arcatao', state_id: 3 },
    { id: 44, name: 'Azacualpa', state_id: 3 },
    { id: 45, name: 'Chalatenango', state_id: 3 },
    { id: 46, name: 'Comalapa', state_id: 3 },
    { id: 47, name: 'Citalá', state_id: 3 },
    { id: 48, name: 'Concepción Quezaltepeque', state_id: 3 },
    { id: 49, name: 'Dulce Nombre de María', state_id: 3 },
    { id: 50, name: 'El Carrizal', state_id: 3 },
    { id: 51, name: 'El Paraíso', state_id: 3 },
    { id: 52, name: 'La Laguna', state_id: 3 },
    { id: 53, name: 'La Palma', state_id: 3 },
    { id: 54, name: 'La Reina', state_id: 3 },
    { id: 55, name: 'Las Vueltas', state_id: 3 },
    { id: 56, name: 'Nueva Concepción', state_id: 3 },
    { id: 57, name: 'Nueva Trinidad', state_id: 3 },
    { id: 58, name: 'Nombre de Jesús', state_id: 3 },
    { id: 59, name: 'Ojos de Agua', state_id: 3 },
    { id: 60, name: 'Potonico', state_id: 3 },
    { id: 61, name: 'San Antonio de la Cruz', state_id: 3 },
    { id: 62, name: 'San Antonio Los Ranchos', state_id: 3 },
    { id: 63, name: 'San Fernando', state_id: 3 },
    { id: 64, name: 'San Francisco Lempa', state_id: 3 },
    { id: 65, name: 'San Francisco Morazán', state_id: 3 },
    { id: 66, name: 'San Ignacio', state_id: 3 },
    { id: 67, name: 'San Isidro Labrador', state_id: 3 },
    { id: 68, name: 'San José Cancasque', state_id: 3 },
    { id: 69, name: 'San José Las Flores', state_id: 3 },
    { id: 70, name: 'San Luis del Carmen', state_id: 3 },
    { id: 71, name: 'San Miguel de Mercedes', state_id: 3 },
    { id: 72, name: 'San Rafael', state_id: 3 },
    { id: 73, name: 'Santa Rita', state_id: 3 },
    { id: 74, name: 'Tejutla', state_id: 3 },
    { id: 75, name: 'Candelaria', state_id: 11 },
    { id: 76, name: 'Cojutepeque', state_id: 11 },
    { id: 77, name: 'El Carmen', state_id: 11 },
    { id: 78, name: 'El Rosario', state_id: 11 },
    { id: 79, name: 'Monte San Juan', state_id: 11 },
    { id: 80, name: 'Oratorio de Concepción', state_id: 11 },
    { id: 81, name: 'San Bartolomé Perulapía', state_id: 11 },
    { id: 82, name: 'San Cristóbal', state_id: 11 },
    { id: 83, name: 'San José Guayabal', state_id: 11 },
    { id: 84, name: 'San Pedro Perulapán', state_id: 11 },
    { id: 85, name: 'San Rafael Cedros', state_id: 11 },
    { id: 86, name: 'San Ramón', state_id: 11 },
    { id: 87, name: 'Santa Cruz Analquito', state_id: 11 },
    { id: 88, name: 'Santa Cruz Michapa', state_id: 11 },
    { id: 89, name: 'Suchitoto', state_id: 11 },
    { id: 90, name: 'Tenancingo', state_id: 11 },
    { id: 91, name: 'Aguilares', state_id: 12 },
    { id: 92, name: 'Apopa', state_id: 12 },
    { id: 93, name: 'Ayutuxtepeque', state_id: 12 },
    { id: 94, name: 'Cuscatancingo', state_id: 12 },
    { id: 95, name: 'Ciudad Delgado', state_id: 12 },
    { id: 96, name: 'El Paisnal', state_id: 12 },
    { id: 97, name: 'Guazapa', state_id: 12 },
    { id: 98, name: 'Ilopango', state_id: 12 },
    { id: 99, name: 'Tonacatepeque', state_id: 12 },
    { id: 100, name: 'Mejicanos', state_id: 12 },
    { id: 101, name: 'Nejapa', state_id: 12 },
    { id: 102, name: 'Panchimalco', state_id: 12 },
    { id: 103, name: 'Rosario de Mora', state_id: 12 },
    { id: 104, name: 'San Marcos', state_id: 12 },
    { id: 105, name: 'San Martín', state_id: 12 },
    { id: 106, name: 'San Salvador', state_id: 12 },
    { id: 107, name: 'Santiago Texacuangos', state_id: 12 },
    { id: 108, name: 'Santo Tomás', state_id: 12 },
    { id: 109, name: 'Soyapango', state_id: 12 },
    { id: 110, name: 'Antiguo Cuscatlán', state_id: 1 },
    { id: 111, name: 'Chiltiupán', state_id: 1 },
    { id: 112, name: 'Ciudad Arce', state_id: 1 },
    { id: 113, name: 'Colón', state_id: 1 },
    { id: 114, name: 'Comasagua', state_id: 1 },
    { id: 115, name: 'Huizúcar', state_id: 1 },
    { id: 116, name: 'Jayaque', state_id: 1 },
    { id: 117, name: 'Jicalapa', state_id: 1 },
    { id: 118, name: 'La Libertad', state_id: 1 },
    { id: 119, name: 'Santa Tecla', state_id: 1 },
    { id: 120, name: 'Nuevo Cuscatlán', state_id: 1 },
    { id: 121, name: 'San Juan Opico', state_id: 1 },
    { id: 122, name: 'Quezaltepeque', state_id: 1 },
    { id: 123, name: 'Sacacoyo', state_id: 1 },
    { id: 124, name: 'San José Villanueva', state_id: 1 },
    { id: 125, name: 'San Matías', state_id: 1 },
    { id: 126, name: 'San Pablo Tacachico', state_id: 1 },
    { id: 127, name: 'Tamanique', state_id: 1 },
    { id: 128, name: 'Talnique', state_id: 1 },
    { id: 129, name: 'Teotepeque', state_id: 1 },
    { id: 130, name: 'Tepecoyo', state_id: 1 },
    { id: 131, name: 'Zaragoza', state_id: 1 },
    { id: 132, name: 'Apastepeque', state_id: 14 },
    { id: 133, name: 'Guadalupe', state_id: 14 },
    { id: 134, name: 'San Cayetano Istepeque', state_id: 14 },
    { id: 135, name: 'San Esteban Catarina', state_id: 14 },
    { id: 136, name: 'San Ildefonso', state_id: 14 },
    { id: 137, name: 'San Lorenzo', state_id: 14 },
    { id: 138, name: 'San Sebastián', state_id: 14 },
    { id: 139, name: 'San Vicente', state_id: 14 },
    { id: 140, name: 'Santa Clara', state_id: 14 },
    { id: 141, name: 'Santo Domingo', state_id: 14 },
    { id: 142, name: 'Tecoluca', state_id: 14 },
    { id: 143, name: 'Tepetitán', state_id: 14 },
    { id: 144, name: 'Verapaz', state_id: 14 },
    { id: 145, name: 'Cinquera', state_id: 5 },
    { id: 146, name: 'Dolores', state_id: 5 },
    { id: 147, name: 'Guacotecti', state_id: 5 },
    { id: 148, name: 'Ilobasco', state_id: 5 },
    { id: 149, name: 'Jutiapa', state_id: 5 },
    { id: 150, name: 'San Isidro', state_id: 5 },
    { id: 151, name: 'Sensuntepeque', state_id: 5 },
    { id: 152, name: 'Tejutepeque', state_id: 5 },
    { id: 153, name: 'Victoria', state_id: 5 },
    { id: 154, name: 'Cuyultitán', state_id: 13 },
    { id: 155, name: 'El Rosario', state_id: 13 },
    { id: 156, name: 'Jerusalén', state_id: 13 },
    { id: 157, name: 'Mercedes La Ceiba', state_id: 13 },
    { id: 158, name: 'Olocuilta', state_id: 13 },
    { id: 159, name: 'Paraíso de Osorio', state_id: 13 },
    { id: 160, name: 'San Antonio Masahuat', state_id: 13 },
    { id: 161, name: 'San Emigdio', state_id: 13 },
    { id: 162, name: 'San Francisco Chinameca', state_id: 13 },
    { id: 163, name: 'San Juan Nonualco', state_id: 13 },
    { id: 164, name: 'San Juan Talpa', state_id: 13 },
    { id: 165, name: 'San Juan Tepezontes', state_id: 13 },
    { id: 166, name: 'San Luis Talpa', state_id: 13 },
    { id: 167, name: 'San Luis La Herradura', state_id: 13 },
    { id: 168, name: 'San Miguel Tepezontes', state_id: 13 },
    { id: 169, name: 'San Pedro Masahuat', state_id: 13 },
    { id: 170, name: 'San Pedro Nonualco', state_id: 13 },
    { id: 171, name: 'San Rafael Obrajuelo', state_id: 13 },
    { id: 172, name: 'Santa María Ostuma', state_id: 13 },
    { id: 173, name: 'Santiago Nonualco', state_id: 13 },
    { id: 174, name: 'Tapalhuaca', state_id: 13 },
    { id: 175, name: 'Zacatecoluca', state_id: 13 },
    { id: 176, name: 'Alegría', state_id: 8 },
    { id: 177, name: 'Berlín', state_id: 8 },
    { id: 178, name: 'California', state_id: 8 },
    { id: 179, name: 'Concepción Batres', state_id: 8 },
    { id: 180, name: 'El Triunfo', state_id: 8 },
    { id: 181, name: 'Ereguayquín', state_id: 8 },
    { id: 182, name: 'Estanzuelas', state_id: 8 },
    { id: 183, name: 'Jiquilisco', state_id: 8 },
    { id: 184, name: 'Jucuapa', state_id: 8 },
    { id: 185, name: 'Jucuarán', state_id: 8 },
    { id: 186, name: 'Mercedes Umaña', state_id: 8 },
    { id: 187, name: 'Nueva Granada', state_id: 8 },
    { id: 188, name: 'Ozatlán', state_id: 8 },
    { id: 189, name: 'Puerto El Triunfo', state_id: 8 },
    { id: 190, name: 'San Agustín', state_id: 8 },
    { id: 191, name: 'San Buenaventura', state_id: 8 },
    { id: 192, name: 'San Dionisio', state_id: 8 },
    { id: 193, name: 'San Francisco Javier', state_id: 8 },
    { id: 194, name: 'Santa Elena', state_id: 8 },
    { id: 195, name: 'Santa María', state_id: 8 },
    { id: 196, name: 'Santiago de María', state_id: 8 },
    { id: 197, name: 'Tecapán', state_id: 8 },
    { id: 198, name: 'Usulután', state_id: 8 },
    { id: 199, name: 'Carolina', state_id: 9 },
    { id: 200, name: 'Chapeltique', state_id: 9 },
    { id: 201, name: 'Chinameca', state_id: 9 },
    { id: 202, name: 'Chirilagua', state_id: 9 },
    { id: 203, name: 'Ciudad Barrios', state_id: 9 },
    { id: 204, name: 'Comacarán', state_id: 9 },
    { id: 205, name: 'El Tránsito', state_id: 9 },
    { id: 206, name: 'Lolotique', state_id: 9 },
    { id: 207, name: 'Moncagua', state_id: 9 },
    { id: 208, name: 'Nueva Guadalupe', state_id: 9 },
    { id: 209, name: 'Nuevo Edén de San Juan', state_id: 9 },
    { id: 210, name: 'Quelepa', state_id: 9 },
    { id: 211, name: 'San Antonio del Mosco', state_id: 9 },
    { id: 212, name: 'San Jorge', state_id: 9 },
    { id: 213, name: 'San Gerardo', state_id: 9 },
    { id: 214, name: 'San Luis de la Reina', state_id: 9 },
    { id: 215, name: 'San Miguel', state_id: 9 },
    { id: 216, name: 'San Rafael Oriente', state_id: 9 },
    { id: 217, name: 'Sesori', state_id: 9 },
    { id: 218, name: 'Uluazapa', state_id: 9 },
    { id: 219, name: 'Arambala', state_id: 2 },
    { id: 220, name: 'Cacaopera', state_id: 2 },
    { id: 221, name: 'Chilanga', state_id: 2 },
    { id: 222, name: 'Corinto', state_id: 2 },
    { id: 223, name: 'Delicias de Concepción', state_id: 2 },
    { id: 224, name: 'El Divisadero', state_id: 2 },
    { id: 225, name: 'El Rosario', state_id: 2 },
    { id: 226, name: 'Gualococti', state_id: 2 },
    { id: 227, name: 'Guatajiagua', state_id: 2 },
    { id: 228, name: 'Joateca', state_id: 2 },
    { id: 229, name: 'Jocoaitique', state_id: 2 },
    { id: 230, name: 'Jocoro', state_id: 2 },
    { id: 231, name: 'Lolotiquillo', state_id: 2 },
    { id: 232, name: 'Meanguera', state_id: 2 },
    { id: 233, name: 'Osicala', state_id: 2 },
    { id: 234, name: 'Perquín', state_id: 2 },
    { id: 235, name: 'San Carlos', state_id: 2 },
    { id: 236, name: 'San Fernando', state_id: 2 },
    { id: 237, name: 'San Francisco Gotera', state_id: 2 },
    { id: 238, name: 'San Isidro', state_id: 2 },
    { id: 239, name: 'San Simón', state_id: 2 },
    { id: 240, name: 'Sensembra', state_id: 2 },
    { id: 241, name: 'Sociedad', state_id: 2 },
    { id: 242, name: 'Torola', state_id: 2 },
    { id: 243, name: 'Yamabal', state_id: 2 },
    { id: 244, name: 'Yoloaiquín', state_id: 2 },
    { id: 245, name: 'Anamorós', state_id: 10 },
    { id: 246, name: 'Bolivar', state_id: 10 },
    { id: 247, name: 'Concepción de Oriente', state_id: 10 },
    { id: 248, name: 'Conchagua', state_id: 10 },
    { id: 249, name: 'El Carmen', state_id: 10 },
    { id: 250, name: 'El Sauce', state_id: 10 },
    { id: 251, name: 'Intipucá', state_id: 10 },
    { id: 252, name: 'La Unión', state_id: 10 },
    { id: 253, name: 'Lislique', state_id: 10 },
    { id: 254, name: 'Meanguera del Golfo', state_id: 10 },
    { id: 255, name: 'Nueva Esparta', state_id: 10 },
    { id: 256, name: 'Pasaquina', state_id: 10 },
    { id: 257, name: 'Polorós', state_id: 10 },
    { id: 258, name: 'San Alejo', state_id: 10 },
    { id: 259, name: 'San José', state_id: 10 },
    { id: 260, name: 'Santa Rosa de Lima', state_id: 10 },
    { id: 261, name: 'Yayantique', state_id: 10 },
    { id: 262, name: 'Yucuaiquín', state_id: 10 },
  ]);
};
